-- AICharacter: Test

-- Test CHARACTER SCRIPT
-- Created by Matthew Jack

-- Used for testing, especially CE3 features

AICharacter.Test = {

	Class = UNIT_CLASS_INFANTRY,
	
	-------------------------------------------------------------------------------------------------------
	AnyBehavior = {
		
		-- Core
		OnGroupMemberDiedNearest 	= "",
		OnLowHideSpot	= "",
		OnEnemySeen = "",
		OnReceivingDamage	= "",
		OnReload = "",
		OnSomethingSeen = "",
		OnThreateningSoundHeard = "",
		OnAtEntity = "",	
		OnNoHidingPlace = "",
		OnNoTarget = "",
		OnBulletRain = "",
		OnCloseContact = "",
		OnDamage = "",
		OnDoneCapture = "",
		OnEnemyDamage = "",
		OnGrenadeSeen	= "",
		OnGroupMemberDied	= "",
		OnInterestingSoundHeard = "",
		taking_fire = "",
		bulletrain = "",
		OnNearMiss = "",
		GET_ALERTED_RESPONSE = "",
		HEADS_UP_GUYS		= "",
		INCOMING_FIRE		= "",
		END_PEEK = "",
		HIDE_AVAILABLE = "",
		RETURN_TO_FIRST = "FIRST",
		
	
		-- Switching between GoonAdaptable combat modes
		GA_FLANKER = "",
		GA_COVER = "",
		GA_APPROACH = "",
		GA_BODYGUARD = "",
		GA_SEARCH = "",
		GA_DEFEND = "",
		GA_RUNTOPICKUPPOINT = "",
		GA_RESERVE = "",
		
		
		-- Flowgraph commands
		FG_TO_ALERT = "",
 		FG_TO_ATTACK = "",
 		FG_TO_DUMB = "",
 		FG_TO_IDLE = "",
 		FG_TO_SLAVESHOOT = "",
 		FG_TO_STRICTBRIEFATTACK = "",
 		FG_TO_TOTALLYDUMB = "",
 				
		-- Not used yet
		back_to			= "BROKEN",
		BackToJob			 = "BROKEN",
		BackToPrevious = "BROKEN",
		BACKOFF = "BROKEN",
		be_alerted			= "BROKEN",
		BREAK_TEAM = "BROKEN",		
		ENTERING_VEHICLE = "BROKEN",
		entered_vehicle = "BROKEN",
		exited_vehicle 	= "BROKEN",
		GO_ATTACK    	= "BROKEN",
		CHECK_FOR_TARGET = "BROKEN",
		GOING_TO_TRIGGER = "BROKEN",
		GO_INTO_WAIT_STATE  = "BROKEN",
		GROUP_MERGE	= "BROKEN",
		HOLD_POSITION		= "BROKEN",
		IGNORE_ALL_ELSE         = "BROKEN",
		INVESTIGATE_DONE = "BROKEN",
		KEEP_FORMATION		= "BROKEN",
		LEFT_LEAN_ENTER		= "BROKEN",
		NORMAL_THREAT_SOUND 	= "BROKEN",
		ORDER_ENTER_VEHICLE = "BROKEN",	
		ORDER_FIRE = "BROKEN",
		ORDER_FOLLOW = "BROKEN",
		ORDER_FOLLOW_HIDE		="BROKEN",
		ORDER_FORM		="BROKEN",
		ORDER_HIDE = "BROKEN",
		ORDER_HOLD	 = "BROKEN",
		ORDER_MOVE	 = "BROKEN",	
		ORDER_PLANT_BOMB = "BROKEN",	
		ORDER_SEARCH = "BROKEN",
		ORDER_USE_RPG = "BROKEN",
		OnLeadFormationPath = "BROKEN",
		OnLeaderDead = "BROKEN",
		OnNoFormationPoint 	= "BROKEN",
		PROTECT_THIS_POINT = "BROKEN",		
		RESERVE = "",
		RESUME_FOLLOWING	= "BROKEN",
		RETREAT_NOW	= "BROKEN",
		RETREAT_NOW_PHASE2	= "BROKEN",
		RIGHT_LEAN_ENTER	= "BROKEN",
		RUSH_TARGET = "BROKEN",
		SEARCH_AROUND	= "BROKEN",
		SELECT_BLACK		= "BROKEN",
		SELECT_RED		= "BROKEN",
		SPECIAL_DUMB	= "BROKEN",
		SPECIAL_FOLLOW 	= "BROKEN",
		SPECIAL_HOLD	= "BROKEN",
		SPECIAL_LEAD 	= "BROKEN",
		SPECIAL_STOPALL	= "BROKEN",
		START_CLIMBING = "BROKEN",
		START_SWIMMING  = "BROKEN",
		STOP_CLIMBING  = "BROKEN",
		STOP_RUSH = "BROKEN",
		STOP_SWIMMING  = "BROKEN",
		SWITCH_TO_RUN_TO_FRIEND = "BROKEN",
		TO_ATTACK		= "BROKEN",
		TO_PREVIOUS 		= "BROKEN",
		USE_MOUNTED_WEAPON = "BROKEN",
		entered_vehicle	="BROKEN",
		exited_vehicle	="BROKEN",
		exited_vehicle_investigate = "BROKEN",
	},
	
	-------------------------------------------------------------------------------------------------------
		
	-- Idle, no guns
	GoonTestIdle = {
		go_combat = "TestCombat",
		GET_ALERTED	 		= "",
		GET_ALERTED_RESPONSE	 		= "",
		OnThreateningSoundHeard = "",
		OnBulletRain		= "",
		OnEnemyDamage		= "",
		OnInterestingSoundHeard = "",
		OnEnemySeen    = "",
		OnSomebodyDied	= "",
		OnSomethingSeen	= "",
		HEADS_UP_GUYS	= "",
		GET_ALERTED	 = "",
		OnAbortCapture = "",
	},
	
	-- Combat, lots of guns
	GoonTestCombat = {
		go_idle = "GoonTestIdle",
		GET_ALERTED	 		= "",
		GET_ALERTED_RESPONSE	 		= "",
		OnThreateningSoundHeard = "",
		OnBulletRain		= "",
		OnEnemyDamage		= "",
		OnInterestingSoundHeard = "",
		OnEnemySeen    = "",
		OnSomebodyDied	= "",
		OnSomethingSeen	= "",
		HEADS_UP_GUYS	= "",
		GET_ALERTED	 = "",
		OnAbortCapture = "",
	},
}